var GAME_LEVELS = [
  ["  x       m             m  m                     m                     m     x  ",
   "  x                                                                          x  ",
   "  x                                                                          x  ",
   "  x                                                                          x  ",
   "  x                                                                          x  ",
   "  x                                                                          x  ",
   "  x                                                                          x  ",
   "  x                                                 xxxxxx     xxxx          x  ",
   "  x                  xxx     xxxxxxx                     x!!!!!x             x  ",
   "  x                                x                     x!!!!!x             x  ",
   "  x @                              x       xxxxx         x!!!!!x        yy   x  ",
   "  x                                x     xxx             xxxxxxx             x  ",
   "  x     o                          xxxxxxx                                   x  ",
   "  xxx        yy             xxx               xxx                  yy        x  ",
   "    x                         xxx           xxx                           xxxx  ",
   "    xxxx           xxxx                   xxx       xxx                xxxx     ",
   "       xxxx        x  xxx                           x xxx           xxxx        ",
   "          xxxxxx!!!x    xxxxxxxxxxxxxxxxxxxxx       x   xxxxxxxxxxxxx           ",
   "               x!!!x                        x       x                           ",
   "               x!!!x                        x!!!!!!!x                           ",
   "               xxxxx                        x!!!!!!!x                           ",
   "                                            x!!!!!!!x                           ",
   "                                            xxxxxxxxx                           ",
   "                                                                                "],
  ["x                    m             m                                           m                            m   m ",
   "x                                                                                                                 ",
   "x                                                                                                                 ",
   "x                                                                                                                 ",
   "x                                                                                                                 ",
   "x                                                                                                                 ",
   "x                                                                                xxxxxxxxxxxxxx                   ",
   "x                                                                                             x               o   ",
   "x                                                                                             x                   ",
   "x                                                 xxx!!!!!!xxxxxx!!!!!!xxx                    x o                 ",
   "x                                                   xxx!!!!!!!!!!!!!!!xx                      xxxxxxxxxxxxx       ",
   "x                                                     xxxxxxxxxxxxxxx!x                                           ",
   "x                      xxxxxxxxx                                     m                                            ",
   "x                                           xxxxxx                                     x                          ",
   "x                                                xxx                         x         x                          ",
   "x                                                  xxxxxxxxx                 x         x                          ",
   "x                                          xxxx    x                         x         xxxx                       ",
   "x                             xxxx   xxx      x  o x                         x            x                       ",
   "x         xxxxxxxx               x   x o      xxxxxx     x                   x    x     o x                       ",
   "x         x                    o x   xx                  x                   x         xxxx      xx               ",
   "x         x o               xxxxxx    x                  x                 xxx         x                          ",
   "x         xxxxx                       xxxxxxxx  xx                           x         x                          ",
   "x         x                                  x  x    o                       x         x                     o    ",
   "x         x           xxx!!!!!!!!xxx            x       x                    x         x                          ",
   "x         x             xxxxxxxxxx      xxx     xxxxxxxxx             o      x         x                          ",
   "x         x  xx                 xx o                                         x         x               yyyxxxxxxxx",
   "x  @      x                      xxxx                              xxxxxxx   x         x                          ",
   "xyyyyyyyyyx!!!!!xxxxxx              xxxxxxxxxxxxxxx                          xxxyyyyyxxx                          ",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!"],
  ["  x               m                                                  m m                    m             x   ",
   "  x                                                                                                       x   ",
   "  x                                   o      o    o                              o o                      x   ",
   "  x                                                                                                       x   ",
   "  x                        xxx  xxx  xxx   xxxx  xxx                           xxxxxxxx                   x   ",
   "  x  o                 xx                              xxxx                                               x   ",
   "  x         xx                                                                                            x   ",
   "  x                                                                                                       x   ",
   "  x                                                                                                       x   ",
   "  x                                                                                                       x   ",
   "  x                                                                                                       x   ",
   "  x xxx                                                                                                   x   ",
   "  x                                                                        xxx                            x   ",
   "  x                                                                                                       x   ",
   "  x                            xxx    xxx                                                                 x   ",
   "  x                                                                                         xx            x   ",
   "  x                                                                                                       x   ",
   "  x        xxxxxxxxxxx                                                                                    x   ",
   "  x                                                                                                       x   ",
   "  x                                        xxxxxx     xxxxxxxx                                            x   ",
   "  x                                        x                                                              x   ",
   "  x                                        x                                 xxx                          x   ",
   "  x                                        x                                                              x   ",
   "  x                                        x                 xxx                                          x   ",
   "  x                                        x                                                              x   ",
   "  x                                        x          xxxx                 xxxxxx                         x   ",
   "  x                                        x          x                                                   x   ",
   "  x                                        x          x           xxx                                     x   ",
   "  x                                        x          x                                                   x   ",
   "  x                                        x          x                                                   x   ",
   "  x                                        x          x                                                   x   ",
   "  x                                        x   xxxxxxxx                                                   x   ",
   "  x                                                                                  xxx                  x   ",
   "  x                                                                                                       x   ",
   "  x                                                                                                       x   ",
   "  x                                                                      xxxxx                            x   ",
   "  x                                                                                                       x   ",
   "  x                                                                                                       x   ",
   "  x                                                                                                       x   ",
   "  x                                                                                                       x   ",
   "  x                                  xxxxxx                         xxxxxxxxxxx                           x   ",
   "  x                                                                                                       x   ",
   "  x                    xxxxx                                                                              x   ",
   "  x      @       xxxxxxxxxxx                                                                              x   ",
   "!!xyyyyyyyyyxxxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!xxxxyyyxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxxxxxxxxxxxxxxxxx!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"],
  ["                                                                                                  xxx x       ",
   "                                                                                                      x       ",
   "                                                                                                  xxxxx       ",
   "                                                                                                  x           ",
   "                                                                                                  x xxx       ",
   "                          o                                                                       x x x       ",
   "                                                                                             o o oxxx x       ",
   "                   xxx                                                                                x       ",
   "       !  o  !                                                xxxxx xxxxx xxxxx xxxxx xxxxx xxxxx xxxxx       ",
   "       x     x                                                x   x x   x x   x x   x x   x x   x x           ",
   "       x= o  x            x                                   xxx x xxx x xxx x xxx x xxx x xxx x xxxxx       ",
   "       x     x                                                  x x   x x   x x   x x   x x   x x     x       ",
   "       !  o  !            o                                  xxxx xxxxx xxxxx xxxxx xxxxx xxxxx xxxxxxx       ",
   "                                                                                                              ",
   "          o              xxx                              xx                                                  ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                      xx                                                      ",
   "                   xxx         xxx                                                                            ",
   "                                                                                                              ",
   "                          o                                                     x      x                      ",
   "                                                          xx     xx                                           ",
   "             xxx         xxx         xxx                                 x                  x                 ",
   "                                                                                                              ",
   "                                                                 ||                                           ",
   "  xxxxxxxxxxx                                                                                                 ",
   "  x         x o xxxxxxxxx o xxxxxxxxx o xx                                                x                   ",
   "  x         x   x       x   x       x   x                 ||                  x     x                         ",
   "  x  @      xxxxx   o   xxxxx   o   xxxxx                                                                     ",
   "  xxxxxxx                                     xxxxx       xx     xx     xxx                                   ",
   "        x=                  =                =x   x                     xxx                                   ",
   "        xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   x!!!!!!!!!!!!!!!!!!!!!xxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "                                                  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                                              "]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
