var GAME_LEVELS = [
  ["  x       m             m  m                     m                     m     x  ",
   "  x                                                         o                x  ",
   "  x                                                                          x  ",
   "  x                                                                          x  ",
   "  x                                                                          x  ",
   "  x                                                                          x  ",
   "  x            o                                                             x  ",
   "  x                                                  xxxxx     xxxx          x  ",
   "  x                  xxx     xxxxxxx                     x!!!!!x             x  ",
   "  x                                x                     x!!!!!x             x  ",
   "  x @                         o    x       xxxx          x!!!!!x        yy   x  ",
   "  x                                x     xxx             xxxxxxx             x  ",
   "  x                                xxxxxxx                                   x  ",
   "  xxx         yy            xxx               xxx                  yy        x  ",
   "    x                         xxx           xxx               o           xxxx  ",
   "    xxxx           xxxx                   xxx                          xxxx     ",
   "       xxxx        x  xxx                 x         xxxxx           xxxx        ",
   "          xxxxxx!!!x    xxxxxxxxxxxxxxxxxxx         x   xxxxxxxxxxxxx           ",
   "               x!!!x                      x         x                           ",
   "               x!!!x                      x!!!!!!!!!x                           ",
   "               xxxxx                      x!!!!!!!!!x                           ",
   "                                          x!!!!!!!!!x                           ",
   "                                          xxxxxxxxxxx                           ",
   "                                                                                "],
  ["x                    m             m                                           m                            m   m ",
   "x                                                                                                                 ",
   "x                                                                                                                 ",
   "x                                                                                                                 ",
   "x                                                                                                                 ",
   "x                                                                                                                 ",
   "x                                                                                xxxxxxxxxxxxxx                   ",
   "x                                                                                             x               o   ",
   "x                                                                                             x                   ",
   "x                                                 xxx!!!!!!xxxxxx!!!!!!xxx                    x o                 ",
   "x                                                   xxx!!!!!!!!!!!!!!!xx                      xxxxxxxxxxxxx       ",
   "x                                                     xxxxxxxxxxxxxxx!x                                           ",
   "x                      xxxxxxxxx                                     m                                            ",
   "x                                           xxxxxx                                     x                          ",
   "x                                                xxx                         x         x                          ",
   "x                                                  xxxxxxxxx                 x         x                          ",
   "x                                          xxxx    x                         x         xxxx                       ",
   "x                             xxxx   xxx      x  o x                         x            x                       ",
   "x         xxxxxxxx               x   x o      xxxxxx     x                   x    x     o x                       ",
   "x         x                    o x   xx                  x                   x         xxxx      xx               ",
   "x         x o               xxxxxx    x                  x                 xxx         x                          ",
   "x         xxxxx                       xxxxxxxx  xx                           x         x                          ",
   "x         x                                  x  x    o                       x         x                     o    ",
   "x         x           xxx!!!!!!!!xxx            x       x                    x         x                          ",
   "x         x             xxxxxxxxxx      xxx     xxxxxxxxx             o      x         x                          ",
   "x         x  xx                 xx o                                         x         x               yyyxxxxxxxx",
   "x  @      x                      xxxx                              xxxxxxx   x         x                          ",
   "xyyyyyyyyyx!!!!!xxxxxx              xxxxxxxxxxxxxxx                          xxxyyyyyxxx                          ",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!"],
  ["  x              m                                                   m m                       m     m       x",
   "  x                                                                                               m          x",
   "  x                                o      o      o                               o o                         x",
   "  x                                                                                                          x",
   "  x                     xxx  xxx  xxx   xxxxx   xxx                            xxxxxxxx                      x",
   "  x  o             xx                                 xxxx                                                   x",
   "  x         xx                                                                                               x",
   "  x                                                                                                          x",
   "  x                                                                                                          x",
   "  x                                                                                                          x",
   "  x                                                                                                          x",
   "  x xxx                                                                                                      x",
   "  x                                    o                                   xxx                          o    x",
   "  x                                                                                                          x",
   "  x                            xxx    xxx                                                                    x",
   "  x                                                                                         xxxxxxxxxxxxxx   x",
   "  x                                                                                                          x",
   "  x        xxxxxxxxxxx                                                                                       x",
   "  x                                                                                                    xxx   x",
   "  x                                        xxxxxx     xxxxxxxx                                               x",
   "  x                                        x                                                                 x",
   "  x                                        x                                 xxx                             x",
   "  x                                        x                                                              xxxx",
   "  x                                        x                 xxx                                             x",
   "  x                                        x                                                                 x",
   "  x                                        x          xxxx                 xxxxxx                       x    x",
   "  x                                        x          x                                                      x",
   "  x                                        x          x           xxx                                x       x",
   "  x                                        x          x                                                      x",
   "  x                                        x          x                                                      x",
   "  x                                        x          x                                                      x",
   "  x                                        x   xxxxxxxx                                                      x",
   "  x                                                                                  xxx                     x",
   "  x                                                                                                          x",
   "  x                                                                                                          x",
   "  x                                                                      xxxxx                               x",
   "  x                                                                                                          x",
   "  x                                                                                                          x",
   "  x                                                                      o                                   x",
   "  x                                                                                                          x",
   "  x                                  xxxxxx                         xxxxxxxxxxx                              x",
   "  x                     xxxx                                                                                 x",
   "  x                 xxxxxxxx                                                                                 x",
   "  x      @      xxxxxxxxxxxx                                                                                 x",
   "!!xyyyyyyyyyxxxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!xxxxyyyxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxxxxxxxxxxxxxxxxxxxx",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"],
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
